### ISSUE TITLE
blocked domain === domain the site runs on?

### ISSUE THREAD

**Issue by zero-24** [nico3333fr/CSP-useful#44] opened 2018-03-07 19:13 UTC
```
{
    "csp-report": {
        "document-uri": "https://www.example.org/...",
        "referrer": "",
        "violated-directive": "img-src 'self'",
        "original-policy": "default-src 'self';",
        "blocked-uri": "https://www.example.org"
    }
}

UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534+ (KHTML, like Gecko) BingPreview/1.0b

```

Where "example.org" is replaced by the live domain.
I guess it is something about Big Preview but I have no idea wtf is happening there. As 'self' is allowed so the domain the rule run on should be allowed.

**Comment by nico3333fr** [comment] 2018-03-12 13:44
Well, this is a WTF :)

A website tried to embed one of your images without sending a referrer?

**Comment by zero-24** [comment] 2018-03-12 16:36
I think it has something todo with the UserAgent as this just happen with `BingPreview` ;) But I don't understand what is happening there.

**Comment by nico3333fr** [comment] 2018-03-22 13:18
Yes, I was not able to reproduce. :-\

**Comment by zero-24** [comment] 2018-03-22 17:28
How did you try to reproduce it? As I think the issue has something todo with the `BingPreview` Bot.

**Comment by nico3333fr** [comment] 2018-03-23 13:24
Sorry, I didn't understood well, I've tried Bing photo preview. 

How do you reproduce this preview?

**Comment by zero-24** [comment] 2018-03-23 15:42
This the problem i have not found a way to reproduce this issue. On the site i have deployed the rules i was getting this reports lately but i have not figured out how to reproduce this. So i decided to report it here if someone else also got this error in the logs.

**Comment by nico3333fr** [comment] 2018-06-05 14:47
Great, I'm closing this issue, do not hesitate to reopen of open a new one if you have news :)

**Closed by nico3333fr** 2018-06-05 14:47 UTC
Labels: question
